smsworks:
  build: .
  links:
    - rabbitmq
  environment:
    TWILIO_SID:
    TWILIO_TOKEN:
    TWILIO_NUMBERS:
rabbitmq:
  image: rabbitmq:3.4.3-management
  ports:
    - "5672"
    - "15672"
  hostname: rabbitmq
