#!/bin/bash

set -e

if [[ -z $SERVICE ]]; then
  SERVICE=${PWD##*/}
fi

if [[ ! -e ${SERVICE}@.service ]]; then
  buildkite-agent artifact download ${SERVICE}@.service .
fi

fleetctl destroy ${SERVICE}@.service
fleetctl submit ${SERVICE}@.service

echo '--- (re-)starting fleet service instances'
for i in {1..3}; do
  fleetctl destroy ${SERVICE}@$i
  fleetctl start ${SERVICE}@$i
  # TODO: Use consul to see if ${SERVICE}@$i is healthy yet before moving on
done
